#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 15, 2017 07:58:40 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global meas1
    meas1 = StringVar()
    global meas2
    meas2 = StringVar()
    global freq
    freq = StringVar()
    global voltage
    voltage = StringVar()
    global list_sweep_from
    list_sweep_from = StringVar()
    global list_sweep_to
    list_sweep_to = StringVar()
    global list_gen_mode
    list_gen_mode = StringVar()
    global num_of_points
    num_of_points = StringVar()
    global list_progressbar_var
    list_progressbar_var = IntVar()

def command_quit():
    print('e4980al_gui_support.command_quit')
    sys.stdout.flush()

def command_save():
    print('e4980al_gui_support.command_save')
    sys.stdout.flush()

def start_list_measure():
    print('e4980al_gui_support.start_list_measure')
    global list_sweep_from
    print(list_sweep_from.get())
    sys.stdout.flush()

def start_single_measure():
    print('e4980al_gui_support.start_single_measure')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import e4980al_gui
    e4980al_gui.vp_start_gui()

